import { useState } from "react";
import { colors, radii, spacing, typography } from "../design-system/tokens";
import { EmptyState } from "../design-system/components/feedback";

function Pending({ children, label }: { children: React.ReactNode; label: string }) { return <span title="Integração pendente" style={{ display: "inline-flex", cursor: "not-allowed" }}><button type="button" disabled aria-label={label} style={{ padding: "8px 11px", border: `1px solid ${colors.border}`, borderRadius: radii.md, background: colors.surfaceAlt, color: colors.textMuted, fontFamily: typography.family.ui, fontSize: typography.size.xs, cursor: "not-allowed", opacity: .7 }}>{children}</button></span>; }

export function PlaybooksPage() {
  const [drawerOpen, setDrawerOpen] = useState(true);
  return <div style={{ display: "flex", flexDirection: "column", gap: spacing["4"] }}>
    <header style={{ display: "flex", alignItems: "end", justifyContent: "space-between", gap: spacing["4"], flexWrap: "wrap" }}><div><div style={eyebrow}>AUTOMATION ORCHESTRATION</div><h1 style={titleStyle}>Playbooks</h1><p style={subtitle}>Catálogo e histórico de automações de resposta do SOC.</p></div><Pending label="Criar playbook">Novo playbook</Pending></header>
    <section className="playbook-kpis" style={{ display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: spacing["3"] }}><Metric label="Disponíveis" context="Catálogo pendente" color={colors.accent} /><Metric label="Ativos" context="Status pendente" color={colors.status.online} /><Metric label="Execuções recentes" context="Histórico pendente" color={colors.severity.medium} /><Metric label="Taxa de sucesso" context="Métrica pendente" color={colors.severity.critical} /></section>
    <div className="playbook-workspace" style={{ display: "grid", gridTemplateColumns: drawerOpen ? "minmax(0,1fr) 330px" : "minmax(0,1fr)", overflow: "hidden", minHeight: 600, border: `1px solid ${colors.border}`, borderRadius: radii.xl, background: colors.surface }}>
      <section style={{ minWidth: 0 }}><div className="playbook-filters" style={{ display: "grid", gridTemplateColumns: "minmax(220px,1.4fr) repeat(3,minmax(130px,.6fr)) auto", gap: 8, padding: spacing["3"], borderBottom: `1px solid ${colors.borderSubtle}` }}><input aria-label="Buscar playbooks" disabled title="Integração pendente" placeholder="Buscar por nome ou descrição…" style={fieldStyle} /><Select label="Status" /><Select label="Gatilho" /><Select label="Categoria" /><button type="button" onClick={() => setDrawerOpen((value) => !value)} style={toggleStyle}>{drawerOpen ? "Ocultar histórico" : "Mostrar histórico"}</button></div><div style={{ overflowX: "auto" }}><table style={{ width: "100%", minWidth: 880, borderCollapse: "collapse" }}><thead><tr>{["Playbook", "Gatilho", "Última execução", "Sucesso", "Versão", "Status", "Ações"].map((label) => <th key={label} style={thStyle}>{label}</th>)}</tr></thead><tbody><tr><td colSpan={7}><EmptyState title="Nenhum playbook disponível" description="Quando a integração de catálogo estiver disponível, os playbooks aparecerão nesta tabela com status, versão e execuções." compact action={<Pending label="Criar primeiro playbook">Novo playbook</Pending>} /></td></tr></tbody></table></div><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: `${spacing["2"]} ${spacing["3"]}`, borderTop: `1px solid ${colors.borderSubtle}`, color: colors.textMuted, fontSize: typography.size.xs }}><span>0 playbooks</span><span>Catálogo aguardando integração</span></div></section>
      {drawerOpen && <aside className="playbook-drawer" style={{ display: "flex", flexDirection: "column", borderLeft: `1px solid ${colors.border}`, background: `linear-gradient(180deg, ${colors.surface} 0%, color-mix(in srgb, ${colors.background} 44%, ${colors.surface}) 100%)` }}><div style={{ padding: spacing["4"], borderBottom: `1px solid ${colors.borderSubtle}` }}><div style={eyebrow}>EXECUTION HISTORY</div><h2 style={{ margin: "7px 0 0", color: colors.textPrimary, fontSize: typography.size.lg }}>Histórico e detalhes</h2></div><EmptyState title="Selecione um playbook" description="O histórico de execução, gatilho, versão e resultados serão exibidos aqui quando houver dados do catálogo." compact /><div style={{ marginTop: "auto", padding: spacing["3"], borderTop: `1px solid ${colors.borderSubtle}` }}><span style={{ display: "block", marginBottom: 8, color: colors.textMuted, fontSize: 10, letterSpacing: "0.1em" }}>AÇÕES</span><div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}><Pending label="Executar playbook">Executar</Pending><Pending label="Editar playbook">Editar</Pending><Pending label="Duplicar playbook">Duplicar</Pending><Pending label="Habilitar ou desabilitar playbook">Habilitar</Pending></div></div></aside>}
    </div>
    <style>{`@media (max-width:1024px){.playbook-workspace{grid-template-columns:1fr !important}.playbook-drawer{border-left:0 !important;border-top:1px solid var(--color-border)}.playbook-filters{grid-template-columns:repeat(2,minmax(0,1fr)) !important}.playbook-filters>input{grid-column:span 2}} @media (max-width:640px){.playbook-kpis{grid-template-columns:repeat(2,minmax(0,1fr)) !important}.playbook-filters{grid-template-columns:1fr !important}.playbook-filters>input{grid-column:auto}}`}</style>
  </div>;
}
function Metric({ label, context, color }: { label: string; context: string; color: string }) { return <div style={{ padding: spacing["3"], border: `1px solid ${colors.border}`, borderTop: `2px solid ${color}`, borderRadius: radii.lg, background: `linear-gradient(145deg,color-mix(in srgb, ${color} 8%, ${colors.surface}) 0%,${colors.surface} 72%)` }}><strong style={{ color: colors.textPrimary, fontFamily: typography.family.mono, fontSize: typography.size.xl }}>—</strong><span style={{ display: "block", marginTop: 5, color: colors.textSecondary, fontSize: typography.size.xs }}>{label}</span><span style={{ display: "block", marginTop: 3, color: colors.textMuted, fontSize: 10 }}>{context}</span></div>; }
function Select({ label }: { label: string }) { return <select aria-label={`Filtrar por ${label}`} disabled title="Integração pendente" style={fieldStyle}><option>{label}</option></select>; }
const eyebrow = { color: colors.accentHover, fontSize: 10, fontWeight: typography.weight.semibold, letterSpacing: "0.12em" };
const titleStyle = { margin: "6px 0 3px", color: colors.textPrimary, fontSize: typography.size["2xl"], letterSpacing: "-0.035em" };
const subtitle = { margin: 0, color: colors.textMuted, fontSize: typography.size.sm };
const fieldStyle = { minWidth: 0, width: "100%", boxSizing: "border-box" as const, padding: "9px 10px", border: `1px solid ${colors.border}`, borderRadius: radii.md, background: colors.background, color: colors.textMuted, fontFamily: typography.family.ui, fontSize: typography.size.xs, cursor: "not-allowed", opacity: .78 };
const toggleStyle = { padding: "8px 10px", border: `1px solid ${colors.border}`, borderRadius: radii.md, background: colors.surfaceAlt, color: colors.textSecondary, fontFamily: typography.family.ui, fontSize: typography.size.xs, cursor: "pointer" };
const thStyle = { padding: "11px 13px", borderBottom: `1px solid ${colors.border}`, textAlign: "left" as const, color: colors.textMuted, fontSize: 10, fontWeight: typography.weight.semibold, letterSpacing: "0.1em", textTransform: "uppercase" as const, whiteSpace: "nowrap" as const };