/** Detection Rules — dedicated catalog and lifecycle surface. */
import { useEffect, useMemo, useState } from "react";
import { apiClient } from "../api/client";
import { Button } from "../design-system";
import { SeverityBadge } from "../design-system/components/badges";
import { EmptyState, LoadingSkeleton } from "../design-system/components/feedback";
import { colors, spacing } from "../design-system/tokens";
import { useToast } from "../state/toast";

interface RuleDto { rule_id: string; name: string; severity: string; category: string; mitre: string[]; tags: string[]; description: string; enabled: boolean; fire_count: number; last_fired: string | null; }
function formatTime(value: string | null) { if (!value) return "Sem hits"; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : `${String(d.getDate()).padStart(2,"0")}/${String(d.getMonth()+1).padStart(2,"0")} ${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`; }

export function RulesPage() {
  const [rules, setRules] = useState<RuleDto[]>([]); const [loading, setLoading] = useState(true); const { toast } = useToast();
  const loadRules = async () => { setLoading(true); const response = await apiClient.get<{ items: RuleDto[] }>("/soc/rules"); setRules(response.success && response.data ? response.data.items : []); setLoading(false); };
  useEffect(() => { void loadRules(); }, []);
  const summary = useMemo(() => ({ enabled: rules.filter((r) => r.enabled).length, hits: rules.reduce((n, r) => n + r.fire_count, 0), priority: rules.filter((r) => r.severity === "critical" || r.severity === "high").length }), [rules]);
  const toggle = async (rule: RuleDto) => { const response = await apiClient.post(`/soc/rules/${rule.rule_id}/${rule.enabled ? "disable" : "enable"}`); toast(response.success ? `Regra ${rule.enabled ? "desabilitada" : "habilitada"}` : "Falha ao atualizar regra", response.success ? "success" : "error"); if (response.success) await loadRules(); };
  return <div className="rules-page">
    <style>{`.rules-page{display:flex;flex-direction:column;gap:16px}.rules-hero{padding:20px;border:1px solid var(--color-border);border-radius:12px;background:linear-gradient(115deg,color-mix(in srgb,var(--color-accent) 8%,var(--color-surface)) 0%,var(--color-surface) 58%)}.rules-eye{color:var(--color-accent);font-size:10px;font-weight:600;letter-spacing:.12em}.rules-hero h1{margin:6px 0 0;color:var(--color-text-primary);font-size:26px;letter-spacing:-.03em}.rules-hero p{margin:6px 0 0;color:var(--color-text-muted);font-size:13px}.rules-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:18px}.rules-summary div{padding:10px 12px;border:1px solid var(--color-border);border-radius:7px;background:color-mix(in srgb,var(--color-surface-alt) 58%,transparent)}.rules-summary span{display:block;color:var(--color-text-muted);font-size:10px;letter-spacing:.08em;text-transform:uppercase}.rules-summary strong{display:block;margin-top:5px;color:var(--color-text-primary);font:600 20px 'JetBrains Mono',monospace}.rules-list{display:flex;flex-direction:column;gap:10px}.rule-card{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(210px,.8fr) auto;gap:16px;align-items:center;padding:14px 16px;border:1px solid var(--color-border);border-radius:9px;background:linear-gradient(180deg,var(--color-surface),color-mix(in srgb,var(--color-surface-alt) 30%,var(--color-surface)));transition:border-color 120ms cubic-bezier(.2,0,0,1),transform 120ms cubic-bezier(.2,0,0,1)}.rule-card:hover{border-color:color-mix(in srgb,var(--color-accent) 38%,var(--color-border));transform:translateY(-1px)}.rule-meta{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin-bottom:7px}.rule-id,.rule-hit{color:var(--color-text-muted);font:10px 'JetBrains Mono',monospace}.rule-name{color:var(--color-text-primary);font-size:14px;font-weight:600}.rule-description{margin-top:4px;color:var(--color-text-muted);font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.rule-life{display:grid;grid-template-columns:1fr 1fr;gap:7px 12px}.rule-life span{color:var(--color-text-muted);font-size:10px;text-transform:uppercase;letter-spacing:.06em}.rule-life strong{display:block;margin-top:3px;color:var(--color-text-secondary);font:11px 'JetBrains Mono',monospace}.rule-tag{padding:2px 6px;border:1px solid var(--color-border);border-radius:999px;color:var(--color-text-muted);font:10px 'JetBrains Mono',monospace}@media(max-width:900px){.rule-card{grid-template-columns:1fr}}@media(max-width:600px){.rules-summary{grid-template-columns:1fr}}`}</style>
    <section className="rules-hero"><div className="rules-eye">DETECTION ENGINEERING</div><h1>Catálogo de regras</h1><p>Lifecycle, criticidade, cobertura MITRE e volume de hits das detecções ativas.</p><div className="rules-summary"><div><span>Regras ativas</span><strong>{summary.enabled}</strong></div><div><span>Hits registrados</span><strong>{summary.hits}</strong></div><div><span>Alta prioridade</span><strong style={{ color: summary.priority ? colors.severity.high : colors.textPrimary }}>{summary.priority}</strong></div></div></section>
    {loading ? <LoadingSkeleton rows={5} variant="card" /> : rules.length === 0 ? <EmptyState title="Nenhuma regra disponível" description="O catálogo de detecção será exibido quando regras forem cadastradas." /> : <section className="rules-list" aria-label="Catálogo de regras">{rules.map((rule) => <article className="rule-card" key={rule.rule_id}><div><div className="rule-meta"><SeverityBadge severity={rule.severity as any}>{rule.severity}</SeverityBadge><span className="rule-id">{rule.rule_id}</span><span style={{ color: rule.enabled ? colors.status.online : colors.textMuted, fontSize:"11px",fontWeight:600 }}>{rule.enabled ? "ATIVA" : "PAUSADA"}</span></div><div className="rule-name">{rule.name}</div><div className="rule-description">{rule.description || rule.category || "Sem descrição operacional"}</div></div><div className="rule-life"><div><span>Hits</span><strong>{rule.fire_count}</strong></div><div><span>Último hit</span><strong>{formatTime(rule.last_fired)}</strong></div><div><span>Categoria</span><strong>{rule.category || "—"}</strong></div><div><span>MITRE</span><strong>{rule.mitre.length ? rule.mitre.join(", ") : "—"}</strong></div></div><div style={{ display:"flex",justifyContent:"end",gap:spacing["2"],alignItems:"center",flexWrap:"wrap" }}>{rule.tags.slice(0,2).map((tag) => <span className="rule-tag" key={tag}>{tag}</span>)}<Button variant={rule.enabled ? "secondary" : "primary"} onClick={() => void toggle(rule)}>{rule.enabled ? "Desabilitar" : "Habilitar"}</Button></div></article>)}</section>}
  </div>;
}