import { useState } from "react";
import { colors, radii, spacing, typography } from "../design-system/tokens";
import { ThemeSwitch } from "../shell/ThemeSwitch";

type SectionKey = "general" | "appearance" | "users" | "roles" | "api" | "integrations" | "collectors" | "notifications" | "retention" | "security" | "audit" | "system";

const sections: { key: SectionKey; label: string; description: string; glyph: string }[] = [
  { key: "general", label: "General", description: "Workspace e preferências globais", glyph: "G" },
  { key: "appearance", label: "Appearance", description: "Tema e densidade visual", glyph: "A" },
  { key: "users", label: "Users", description: "Diretório de operadores", glyph: "U" },
  { key: "roles", label: "Roles", description: "Perfis e permissões", glyph: "R" },
  { key: "api", label: "API", description: "Tokens e limites de acesso", glyph: "API" },
  { key: "integrations", label: "Integrations", description: "Conectores e ingestão", glyph: "I" },
  { key: "collectors", label: "Collectors", description: "Fontes e capacidade de coleta", glyph: "C" },
  { key: "notifications", label: "Notifications", description: "Canais de alerta", glyph: "N" },
  { key: "retention", label: "Retention", description: "Políticas de retenção", glyph: "RT" },
  { key: "security", label: "Security", description: "Controles da instância", glyph: "S" },
  { key: "audit", label: "Audit", description: "Rastreabilidade administrativa", glyph: "AU" },
  { key: "system", label: "System", description: "Saúde e manutenção", glyph: "S" },
];

const content: Record<SectionKey, { eyebrow: string; title: string; description: string; cards: { title: string; description: string; value: string; status?: string }[] }> = {
  general: { eyebrow: "WORKSPACE GOVERNANCE", title: "General", description: "Identidade e contexto padrão deste workspace SOC.", cards: [{ title: "Workspace", description: "Identificador apresentado em toda a operação.", value: "EDY / PRIMARY SOC" }, { title: "Fuso horário", description: "Padrão de exibição para timelines e auditoria.", value: "America/Sao_Paulo" }, { title: "Idioma", description: "Linguagem operacional da interface.", value: "Português (Brasil)" }] },
  appearance: { eyebrow: "EXPERIENCE", title: "Appearance", description: "Aparência consistente para o console do analista.", cards: [{ title: "Tema", description: "Alterne o modo visual sem sair do workspace.", value: "Alternância disponível" }, { title: "Densidade", description: "Configuração sugerida para filas operacionais.", value: "Compacta" }, { title: "Movimento", description: "Microinterações respeitam redução de movimento.", value: "Enterprise motion" }] },
  users: { eyebrow: "IDENTITY DIRECTORY", title: "Users", description: "Diretório de usuários preparado para integração de identidade.", cards: [{ title: "Diretório", description: "Fonte de identidade para operadores SOC.", value: "Integração pendente", status: "Pendente" }, { title: "Convites", description: "Provisionamento de novos analistas.", value: "Integração pendente", status: "Pendente" }, { title: "Sessões", description: "Sessões ativas e políticas de expiração.", value: "Integração pendente", status: "Pendente" }] },
  roles: { eyebrow: "ACCESS CONTROL", title: "Roles", description: "Modelo de acesso para ações de detecção e resposta.", cards: [{ title: "RBAC", description: "Perfis como Analyst, Responder e Administrator.", value: "Contrato pendente", status: "Pendente" }, { title: "Escopos", description: "Permissões granulares por domínio SOC.", value: "Contrato pendente", status: "Pendente" }, { title: "Revisão de acesso", description: "Rotina de recertificação de privilégios.", value: "Contrato pendente", status: "Pendente" }] },
  api: { eyebrow: "DEVELOPER ACCESS", title: "API", description: "Chaves, limites e auditoria de chamadas de integração.", cards: [{ title: "API Keys", description: "Credenciais de integração com rotação controlada.", value: "Integração pendente", status: "Pendente" }, { title: "Rate limits", description: "Proteção de endpoints e capacidade do tenant.", value: "Não configurado" }, { title: "Webhooks", description: "Eventos de automação e notificações externas.", value: "Integração pendente", status: "Pendente" }] },
  integrations: { eyebrow: "CONNECTIVITY", title: "Integrations", description: "Conectores de ingestão, identidade e resposta.", cards: [{ title: "Coletores", description: "Fontes de telemetria e estado de ingestão.", value: "Gerenciado pela plataforma" }, { title: "Threat feeds", description: "Feeds externos de indicadores e reputação.", value: "Contrato pendente", status: "Pendente" }, { title: "Resposta", description: "Integrações de contenção e automação.", value: "Contrato pendente", status: "Pendente" }] },
  collectors: { eyebrow: "INGESTION OPERATIONS", title: "Collectors", description: "Visibilidade de fontes, capacidade e falhas de coleta.", cards: [{ title: "Inventário", description: "Coletores registrados pela plataforma.", value: "Consulta pendente", status: "Pendente" }, { title: "Capacidade", description: "Uso, fila e atraso por fonte de ingestão.", value: "Consulta pendente", status: "Pendente" }, { title: "Falhas", description: "Erros de entrega e eventos em quarentena.", value: "Consulta pendente", status: "Pendente" }] },
  notifications: { eyebrow: "OPERATIONAL SIGNALS", title: "Notifications", description: "Políticas de entrega para eventos que precisam de atenção.", cards: [{ title: "Central do SOC", description: "Alertas exibidos no sino do console.", value: "Ativa", status: "Ativo" }, { title: "Escalonamento", description: "Canais externos para alertas críticos.", value: "Integração pendente", status: "Pendente" }, { title: "Silenciamento", description: "Janela operacional para manutenção programada.", value: "Não configurado" }] },
  retention: { eyebrow: "DATA GOVERNANCE", title: "Retention", description: "Políticas de ciclo de vida para dados de segurança.", cards: [{ title: "Eventos", description: "Retenção de telemetria e índices de busca.", value: "Política pendente", status: "Pendente" }, { title: "Evidências", description: "Prazo de guarda de artefatos e anexos.", value: "Política pendente", status: "Pendente" }, { title: "Expurgo", description: "Execução auditável de políticas aprovadas.", value: "Integração pendente", status: "Pendente" }] },
  security: { eyebrow: "INSTANCE SECURITY", title: "Security", description: "Controles necessários para proteger o workspace operacional.", cards: [{ title: "Autenticação", description: "Provedor de identidade e ciclo de sessão.", value: "Integração pendente", status: "Pendente" }, { title: "RBAC", description: "Aplicação de permissões por operador e domínio.", value: "Contrato pendente", status: "Pendente" }, { title: "Secrets", description: "Armazenamento seguro de credenciais de integração.", value: "Integração pendente", status: "Pendente" }] },
  audit: { eyebrow: "ACCOUNTABILITY", title: "Audit", description: "Registro verificável de alterações administrativas e operacionais.", cards: [{ title: "Eventos", description: "Consulta de ações administrativas realizadas.", value: "Contrato pendente", status: "Pendente" }, { title: "Exportação", description: "Entrega controlada de trilhas para auditoria.", value: "Integração pendente", status: "Pendente" }, { title: "Integridade", description: "Proteção e retenção dos registros de auditoria.", value: "Política pendente", status: "Pendente" }] },
  system: { eyebrow: "PLATFORM HEALTH", title: "System", description: "Estado operacional e manutenção da instância.", cards: [{ title: "Ambiente", description: "Identificação da instância atual.", value: "PRIMARY" }, { title: "Health checks", description: "Sinais expostos pela plataforma.", value: "Disponível", status: "Ativo" }, { title: "Auditoria", description: "Retenção e consulta de ações administrativas.", value: "Contrato pendente", status: "Pendente" }] },
};

export function SettingsPage() {
  const [selected, setSelected] = useState<SectionKey>("general");
  const view = content[selected];
  return <div className="settings-layout" style={{ display: "grid", gridTemplateColumns: "260px minmax(0,1fr)", minHeight: 660, overflow: "hidden", border: `1px solid ${colors.border}`, borderRadius: radii.xl, background: colors.surface }}>
    <aside className="settings-nav" style={{ padding: spacing["3"], borderRight: `1px solid ${colors.border}`, background: `linear-gradient(180deg, ${colors.surface} 0%, color-mix(in srgb, ${colors.background} 44%, ${colors.surface}) 100%)` }}><div style={{ padding: `${spacing["2"]} ${spacing["2"]} ${spacing["3"]}` }}><div style={{ color: colors.accentHover, fontSize: 10, fontWeight: typography.weight.semibold, letterSpacing: "0.12em" }}>ADMINISTRATION</div><h1 style={{ margin: "7px 0 0", color: colors.textPrimary, fontSize: typography.size.xl }}>Configurações</h1></div><nav aria-label="Seções de configuração">{sections.map((section) => { const active = selected === section.key; return <button type="button" key={section.key} onClick={() => setSelected(section.key)} className="settings-nav-item" style={{ width: "100%", display: "flex", gap: 10, alignItems: "center", marginBottom: 4, padding: "9px 8px", border: `1px solid ${active ? "color-mix(in srgb, var(--color-accent) 32%, transparent)" : "transparent"}`, borderLeft: `3px solid ${active ? colors.accent : "transparent"}`, borderRadius: radii.md, background: active ? "color-mix(in srgb, var(--color-accent) 9%, transparent)" : "transparent", color: active ? colors.accentHover : colors.textSecondary, cursor: "pointer", textAlign: "left", transition: "background 140ms ease, border-color 140ms ease, transform 140ms ease" }}><span style={{ display: "grid", placeItems: "center", width: 28, height: 28, flex: "none", border: `1px solid ${colors.borderSubtle}`, borderRadius: radii.md, background: colors.surfaceAlt, color: active ? colors.accentHover : colors.textMuted, fontFamily: section.glyph.length > 1 ? typography.family.mono : typography.family.ui, fontSize: section.glyph.length > 1 ? 9 : 11, fontWeight: typography.weight.bold }}>{section.glyph}</span><span><strong style={{ display: "block", color: active ? colors.textPrimary : colors.textSecondary, fontSize: typography.size.sm }}>{section.label}</strong><span style={{ display: "block", marginTop: 2, color: colors.textMuted, fontSize: 10 }}>{section.description}</span></span></button>; })}</nav></aside>
    <section style={{ minWidth: 0, padding: `${spacing["5"]} ${spacing["6"]}`, overflowY: "auto" }}><div style={{ color: colors.accentHover, fontSize: 10, fontWeight: typography.weight.semibold, letterSpacing: "0.12em" }}>{view.eyebrow}</div><h2 style={{ margin: "8px 0 4px", color: colors.textPrimary, fontSize: typography.size["2xl"], letterSpacing: "-0.035em" }}>{view.title}</h2><p style={{ maxWidth: 600, margin: 0, color: colors.textMuted, fontSize: typography.size.sm }}>{view.description}</p>{selected === "appearance" && <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginTop: spacing["5"], padding: spacing["3"], border: `1px solid ${colors.border}`, borderRadius: radii.lg, background: colors.surfaceAlt }}><span><strong style={{ display: "block", color: colors.textPrimary, fontSize: typography.size.sm }}>Alternar tema do console</strong><span style={{ display: "block", marginTop: 3, color: colors.textMuted, fontSize: typography.size.xs }}>A preferência é aplicada imediatamente e preservada neste navegador.</span></span><ThemeSwitch /></div>}<div className="settings-cards" style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: spacing["3"], marginTop: spacing["5"] }}>{view.cards.map((card) => <article key={card.title} style={{ minHeight: 150, padding: spacing["4"], border: `1px solid ${colors.border}`, borderRadius: radii.lg, background: `linear-gradient(145deg, ${colors.surface} 0%, color-mix(in srgb, ${colors.surfaceAlt} 38%, ${colors.surface}) 100%)` }}><span style={{ display: "inline-flex", padding: "3px 6px", borderRadius: 4, color: card.status === "Ativo" ? colors.status.online : colors.textMuted, background: card.status === "Ativo" ? "color-mix(in srgb, var(--status-online) 12%, transparent)" : colors.surfaceAlt, fontSize: 9, fontWeight: typography.weight.semibold, textTransform: "uppercase", letterSpacing: "0.08em" }}>{card.status || "Informação"}</span><h3 style={{ margin: "12px 0 5px", color: colors.textPrimary, fontSize: typography.size.base }}>{card.title}</h3><p style={{ margin: 0, minHeight: 38, color: colors.textMuted, fontSize: typography.size.xs, lineHeight: 1.45 }}>{card.description}</p><strong style={{ display: "block", marginTop: spacing["3"], color: card.status === "Pendente" ? colors.textMuted : colors.textSecondary, fontFamily: typography.family.mono, fontSize: typography.size.xs }}>{card.value}</strong></article>)}</div><div style={{ marginTop: spacing["5"], padding: `${spacing["3"]} ${spacing["4"]}`, border: `1px solid ${colors.borderSubtle}`, borderRadius: radii.lg, color: colors.textMuted, fontSize: typography.size.xs }}>Sinais sem contrato de API aparecem como pendentes. Nenhuma configuração operacional é simulada nesta área.</div></section>
    <style>{`.settings-nav-item:hover{background:color-mix(in srgb,var(--color-accent) 6%,transparent)!important;transform:translateX(1px)}@media(max-width:900px){.settings-layout{grid-template-columns:1fr!important}.settings-nav{border-right:0!important;border-bottom:1px solid var(--color-border)}.settings-nav nav{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px}.settings-nav-item{margin-bottom:0!important}.settings-cards{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:560px){.settings-nav nav,.settings-cards{grid-template-columns:1fr!important}.settings-layout>section{padding:20px!important}}`}</style>
  </div>;
}
